kitti_velodyne_ros:
    velodyne_dir: "/media/tianbot/SSData/dataset/CADCD/object/2019_02_27/velodyne_clear_dsor/"
    times_dir: "/media/tianbot/SSData/dataset/CADCD/object/2019_02_27/timestamps/"
    frequency: 1
kitti_camera_ros:
    camera_dir: "/media/tianbot/SSData/dataset/CADCD/object/2019_02_27/yolo_detection/" #yolov8
    img_path: "/media/tianbot/SSData/dataset/CADCD/object/2019_02_27/image_2/"
    frequency: 1
autoware_tracker:
    cluster:
        iskitti: true
        label_source: "/image_detections"
        extrinsic_calibration: "/media/tianbot/SSData/dataset/CADCD/object/2019_02_27/calib/0013.txt"
        iou_threshold: 0.2
        
        points_node: "/ground_segmentation/nonground"
        # points_node: "/points_raw"
        output_frame: "velodyne"
        cluster_distances: [0.5,0.5,1.2,2.2,2.5]
        cluster_ranges: [10,20,25,40]
        remove_ground: false
        downsample_cloud: true
        leaf_size: 0.1
        
        use_multiple_thres: true

        cluster_size_min: 7
        cluster_size_max: 10000
        clip_min_height: -2.0
        clip_max_height: 1.0
        cluster_merge_threshold: 0.5
        clustering_distance: 0.5
        remove_points_min: 2.0
        remove_points_max: 100.0
        
        keep_lanes: false
        keep_lane_left_distance: 5.0
        keep_lane_right_distance: 5.0

        use_diffnormals: false
        pose_estimation: true

        use_callback: true
        use_camera: true


        

    tracker:
        gating_thres: 9.22
        gate_probability: 0.99
        detection_probability: 0.9
        life_time_thres: 8
        static_velocity_thres: 0.5
        static_num_history_thres: 3
        prevent_explosion_thres: 1000
        merge_distance_threshold: 0.5
        use_sukf: false

        tracking_frame: "/world"
         # namespace: /detection/object_tracker/
        track_probability: 0.7

    
