autoware_tracker:

    cluster:
        label_source: "/image_detections"
        extrinsic_calibration: "/home/tianbot/online_learning_ws_mini/src/autoware_tracker/config/calib/0017.txt"
        iou_threshold: 0.44
        
        points_node: "/points_raw"
        output_frame: "velodyne"

        remove_ground: true

        downsample_cloud: true
        leaf_size: 0.1

        use_multiple_thres: true

        cluster_size_min: 20
        cluster_size_max: 10000
        clip_min_height: -2.0
        clip_max_height: 0.0
        cluster_merge_threshold: 1.5
        clustering_distance: 0.75
        remove_points_min: 2.0
        remove_points_max: 100.0

        keep_lanes: false
        keep_lane_left_distance: 5.0
        keep_lane_right_distance: 5.0

        use_diffnormals: false
        pose_estimation: true

        use_callback: true
        use_camera: true
        velodyne_dir: "/media/lbh/bin/kitti_tracking/data_tracking_velodyne/training/velodyne/"
        # camera_dir: "/media/lbh/bin/kitti_tracking/data_tracking_velodyne/training/detection/" #ground truth
        camera_dir: "/media/lbh/bin/kitti_tracking/data_tracking_velodyne/training/velodyne/txt_0000/" #yolo
        frequency: 2

    tracker:
        gating_thres: 9.22
        gate_probability: 0.99
        detection_probability: 0.9
        life_time_thres: 8
        static_velocity_thres: 0.5
        static_num_history_thres: 3
        prevent_explosion_thres: 1000
        merge_distance_threshold: 0.5
        use_sukf: false

        tracking_frame: "/world"
         # namespace: /detection/object_tracker/
        track_probability: 0.7

    
