kitti_velodyne_ros:
    velodyne_dir: "/media/tianbot/SSData/dataset/iusl_full/velodyne/"
    times_dir: "/media/tianbot/SSData/dataset/iusl_full/timestamps/"
    velodyne_fog_dir: "/media/tianbot/SSData/dataset/iusl_full/noise/"
    isnoise: true
    frequency: 10
    
kitti_camera_ros:
    camera_dir: "/media/tianbot/SSData/dataset/iusl_full/yolo8_detections_merge_0.4/" #yolo
    img_path: "/media/tianbot/SSData/dataset/iusl_full/camera/front/"
    frequency: 10
    




autoware_tracker:
    cluster:
        iskitti: false
        label_source: "/image_detections"
        extrinsic_calibration: "/home/tianbot/online_learning_ws_mini/data_kitti/iusl_key_frame/calib/calib.txt"
        iou_threshold: 0.35
        
        points_node: "/ground_segmentation/nonground"
        # points_node: "/points_raw"
        output_frame: "velodyne"
        
        remove_ground: false 

        downsample_cloud: true
        leaf_size: 0.1

        use_multiple_thres: true
        
        cluster_size_min: 3
        cluster_size_max: 10000
        clip_min_height: -0.8
        clip_max_height: 1.5
        cluster_merge_threshold: 1.2
        clustering_distance: 0.5
        remove_points_min: 0.8
        remove_points_max: 20.0

        keep_lanes: false
        keep_lane_left_distance: 5.0
        keep_lane_right_distance: 5.0

        use_diffnormals: false
        pose_estimation: true

        use_callback: true
        use_camera: true


        

    tracker:
        gating_thres: 9.22
        gate_probability: 0.99
        detection_probability: 0.9
        life_time_thres: 8
        static_velocity_thres: 0.5
        static_num_history_thres: 3
        prevent_explosion_thres: 1000
        merge_distance_threshold: 0.5
        use_sukf: false

        tracking_frame: "/world"
        track_probability: 0.7

    
